source "https://rubygems.org"

ruby '2.2.4'
gem "sinatra", "~>1.4.7"
gem "sinatra-contrib"
gem "erubis"
gem 'pry'
gem 'redcarpet'
gem 'bcrypt'

group :production do 
  gem 'puma'
end

group :test do
  gem 'minitest'
end